// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3U4izcYq8VLK6MSEAahJk9fJw1AF_EGQ',
    appId: '1:829928583492:web:b82f04f6cd51cc61dee711',
    messagingSenderId: '829928583492',
    projectId: 'mivafid-app',
    authDomain: 'mivafid-app.firebaseapp.com',
    storageBucket: 'mivafid-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRz8UQvHj7SoEkFvKeaxLl0z3PUjjm-A',
    appId: '1:829928583492:android:5988a18238034517dee711',
    messagingSenderId: '829928583492',
    projectId: 'mivafid-app',
    storageBucket: 'mivafid-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGAdfh1MikWNYpSnCRJLOzUkDWgQVtOyQ',
    appId: '1:829928583492:ios:eafa0a56a337abdddee711',
    messagingSenderId: '829928583492',
    projectId: 'mivafid-app',
    storageBucket: 'mivafid-app.firebasestorage.app',
    iosBundleId: 'com.mivafid.app',
  );
}
